version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: password
        DATABASE_HOST: db
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY_BASE: your_generated_secret_key
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  postgres_data:
